kind: pipeline
type: kubernetes
name: build

steps:
  - name: test-build
    image: golang:1.13
    commands:
    - go test -v
    - go build -v -o main .

  - name: build-docker
    image: banzaicloud/drone-kaniko
    settings:
      username: eonpatapon
      password:
        from_secret: DOCKER_PASSWORD
      repo: eonpatapon/hello-world
      tags: ${DRONE_COMMIT:0:8}

