kind: pipeline
type: kubernetes
name: build

steps:
  - name: test-build
    image: golang:1.13
    commands:
    - go test -v
    - go build -v -o main .

  - name: build-docker
    image: banzaicloud/drone-kaniko
    settings:
      username: eonpatapon
      password:
        from_secret: DOCKER_PASSWORD
      repo: eonpatapon/hello-world
      tags: ${DRONE_COMMIT:0:8}

trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
type: kubernetes
name: deploy-dev

steps:
  - name: deploy
    image: nixery.dev/shell/kubectl/yq
    environment:
      KUBERNETES_TOKEN:
        from_secret: KUBERNETES_DEV_TOKEN
    commands:
      - export NS=hello-world-pr-${DRONE_PULL_REQUEST}
      - export IMAGE="eonpatapon/hello-world:${DRONE_COMMIT:0:8}"
      - kubectl --token "$${KUBERNETES_TOKEN}" create ns $${NS} || true
      - yq 'select(.kind == "Service") | .metadata.namespace = env.NS' deployment.yaml | kubectl --token "$${KUBERNETES_TOKEN}" apply -f -
      - yq 'select(.kind == "Deployment") | .spec.template.spec.containers[0].image = env.IMAGE | .metadata.namespace = env.NS' deployment.yaml | kubectl --token "$${KUBERNETES_TOKEN}" apply -f -

  - name: test
    image: nixery.dev/shell/curl/gnugrep
    commands:
      - export NS=hello-world-pr-${DRONE_PULL_REQUEST}
      - |
        count=0
        while :
        do
          if curl http://hello-world.$${NS} | grep -q "hello world"; then exit 0; fi
          sleep 1
          count=$(( count + 1 ))
          [ $count -gt 59 ] && exit 1
        done

trigger:
  event:
    - pull_request

depends_on:
  - build

---
kind: pipeline
type: kubernetes
name: deploy-prod

steps:
  - name: deploy-prod
    image: nixery.dev/shell/kubectl/yq
    environment:
      KUBERNETES_TOKEN:
        from_secret: KUBERNETES_DEV_TOKEN
    commands:
      - export NS=hello-world
      - export IMAGE="eonpatapon/hello-world:${DRONE_COMMIT:0:8}"
      - kubectl --token "$${KUBERNETES_TOKEN}" create ns $${NS} || true
      - yq 'select(.kind == "Service") | .metadata.namespace = env.NS' deployment.yaml | kubectl --token "$${KUBERNETES_TOKEN}" apply -f -
      - yq 'select(.kind == "Deployment") | .spec.template.spec.containers[0].image = env.IMAGE | .metadata.namespace = env.NS' deployment.yaml | kubectl --token "$${KUBERNETES_TOKEN}" apply -f -

trigger:
  event:
    - promote
  target:
    - production
